### ISSUE TITLE
Dependencies for jaxns are not properly installed for versions 2.6.4 through 2.6.6

### ISSUE THREAD

**Issue by wcxve** [Joshuaalbert/jaxns#212]
**Describe the bug**
When using `pip install jaxns` to install `jaxns`, its dependencies are not properly installed.

**Expected behavior**
After installation, jaxns should be importable in Python without additional manual dependency installation.

**Observed behavior**
The installation completes successfully, but attempting to import jaxns results in a ModuleNotFoundError due to missing dependencies.

**Minimal Verifiable Complete Example**
```bash
conda create -n jaxns python=3.9 -y
conda activate jaxns
pip install jaxns==2.6.4
python -c "import jaxns"
```

**Output**
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/miniforge3/envs/jaxns/lib/python3.9/site-packages/jaxns/__init__.py", line 3, in <module>
    from jaxns.framework import *
  File "~/miniforge3/envs/jaxns/lib/python3.9/site-packages/jaxns/framework/__init__.py", line 1, in <module>
    from jaxns.framework.bases import *
  File "~/miniforge3/envs/jaxns/lib/python3.9/site-packages/jaxns/framework/bases.py", line 4, in <module>
    import jax.numpy as jnp
ModuleNotFoundError: No module named 'jax'
```

**Affected Versions**
This issue occurs in jaxns versions 2.6.4, 2.6.5, and 2.6.6.

**Comment by Joshuaalbert** [comment]
This is a bug in the pyproject.toml. I spotted this too and plan to push a fix this weekend. CheersJoshOn Dec 6, 2024 18:37, "W.-C. Xue" ***@***.***> wrote:
Describe the bug
When using pip install jaxns to install jaxns, its dependencies are not properly installed.
Expected behavior
After installation, jaxns should be importable in Python without additional manual dependency installation.
Observed behavior
The installation completes successfully, but attempting to import jaxns results in a ModuleNotFoundError due to missing dependencies.
Minimal Verifiable Complete Example
conda create -n jaxns python=3.9 -y
conda activate jaxns
pip install jaxns==2.6.4
python -c "import jaxns"
Output
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/miniforge3/envs/jaxns/lib/python3.9/site-packages/jaxns/__init__.py", line 3, in <module>
    from jaxns.framework import *
  File "~/miniforge3/envs/jaxns/lib/python3.9/site-packages/jaxns/framework/__init__.py", line 1, in <module>
    from jaxns.framework.bases import *
  File "~/miniforge3/envs/jaxns/lib/python3.9/site-packages/jaxns/framework/bases.py", line 4, in <module>
    import jax.numpy as jnp
ModuleNotFoundError: No module named 'jax'

Affected Versions
This issue occurs in jaxns versions 2.6.4, 2.6.5, and 2.6.6.
